name: Refresh events

on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch events on HacPai
      run: curl https://hacpai.com/api/v2/user/88250/events?size=8
